services:
  base:
    image: mariadb
    container_name: maria
    ports:
      - "3306:3306"
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./mariadb/data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wordpress:
    depends_on:
      - base
    image: wordpress:6.8.3-php8.1-fpm
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=base:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes/:rw
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./wordpress:/var/www/html
      - ./themes:/var/www/html/wp-content/themes/:rw
    networks:
      - app-network
  phpmyadmin:
    depends_on:
      - base
    image: phpmyadmin
    ports:
      - 8181:80
    environment:
      - PMA_HOST=base
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    networks:
      - app-network
networks:
  app-network:
    driver: bridge